### PR TITLE
Add resample tutorial

### PR DESCRIPTION
**Pull request by kcpevey**
* add tutorial explaining how to use pyleoclim.Series.resample.

### CODE REVIEW

**Comment by CommonClimate** [comment]
Interesting that `ts5k = ts.resample('5ka').mean()` re-ordered the timeseries, so that the age goes from large to small. I suspect that is because the Resampler works with increasing datetime indices, which in this case means decreasing age.  Should I open an issue about this?

**Comment by CommonClimate** [comment]
- "We've successfully resampled to every 5 years" --> We've successfully resampled to every 5,000 years

- "ts_linear_fill = ts5k.pandas_method(lambda x: x.interpolate(method='linear'))"  --> is it because `ts5k = ts.resample('5ka').interpolate()` doesn't work? (produces a bunch of NaNs) . Should I open an issue about this too?

- Finally,  nice job on the Holoviews example to showcase how to inspect the result. What it highlights for me is (as I've pointed out before) that the default behavior of `resample()` introduces a time lag , which is undesirable:

LR04_resample5klag

On Slack, @MarcoGorelli pointed to a way to shift the index by half an interval (2.5ka in this case) so that the resampled series matches the old one peak to peak (as closely as possible). I suggest this should become the default behavior of `resample()` under the hood.

**Comment by CommonClimate** [comment]
Lastly, if we put this in a JupyterBook, will the HoloViews example render interactively?

**Comment by kcpevey** [comment]
>re-ordered the timeseries, so that the age goes from large to small. I suspect that is because the Resampler works with increasing datetime indices, which in this case means decreasing age. Should I open an issue about this?

Yes, this is part of the pyleoclim code. Looks like it needs the ability to take into account direction if available. 
 https://github.com/LinkedEarth/Pyleoclim_util/blob/Development/pyleoclim/utils/tsbase.py#L334-L341

>"ts_linear_fill = ts5k.pandas_method(lambda x: x.interpolate(method='linear'))" --> is it because ts5k = ts.resample('5ka').interpolate() doesn't work? (produces a bunch of NaNs) . Should I open an issue about this too?

This was the approach that @MarcoGorelli had suggested because "In general, resample.interpolate is going to be quite tricky, given that the datetime index will have a pretty odd frequency". Now that I'm thinking more on it, these two approaches are doing very different things. `ts.resample('5ka').interpolate()` would interpolate between missing resample points with a given method, whereas `ts5k.pandas_method(lambda x: x.interpolate(method='linear'))` interpolates/smooths the results of the resample. Do I have that correct, @MarcoGorelli ? Is it impossible to do `ts.resample('5ka').interpolate()` or is it just going to take significant effort?

>On Slack, @MarcoGorelli pointed to a way to shift the index by half an interval (2.5ka in this case) so that the resampled series matches the old one peak to peak (as closely as possible). I suggest this should become the default behavior of resample() under the hood.

Makes sense. I suggest opening an issue. 

>if we put this in a JupyterBook, will the HoloViews example render interactively?

Good question. I dont know the answer. I can do a small test to find out.

**Comment by kcpevey** [comment]
I checked and a line plot will still be interactive when rendered to html with jupyterbook.

**Pull request merged**
