### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by kcpevey**
* Add CI
  * ensure notebooks are not committed with content
  * ensure that notebooks run without failure
 

The current notebooks do not all run so CI is expected to fail initially. We will correct the failures in a separate PR.

### CODE REVIEW

**Comment by kcpevey** [comment]
This needs to be rebased once #2 is merged.

**Comment by khider** [comment]
I merged the previous pull request.

**Comment by kcpevey** [comment]
Thanks @khider! Just a quick tip on best practices, we try to get a github review "approval" from at least one person before merging :)

**Review by anirrudh — APPROVED** [review]

**Comment by kcpevey** [comment]
The errors are coming from the two notebooks that don't currently run. I'm going to call that a separate (high priority) issue.

**Pull request merged**
